### ISSUE TITLE
Update Readme file

### ISSUE THREAD

**Issue by codemaniac-sahil** [codemaniac-sahil/codemaniac-sahil#1]
Update Readme file for my personal repository.

**Comment by clairecharles** [comment]
Can i work on this @codemaniac-sahil ?

**Comment by codemaniac-sahil** [comment]
Yes @clairecharles

**Comment by bloodmonk7** [comment]
I will suggest you to make this readme file on your own and write about yourself, I can surely help by suggesting you ways to make it look good. @codemaniac-sahil

**Comment by codemaniac-sahil** [comment]
Just write the template
